# with flag_y1_stellarhalo_masked to False

#run: "y3v02-cm-001"
run: "y3v02-sof"

global_seed: 22350


# job setup
jobs:
    # for MOF this refers to the number of FOFs in a chunk,
    # otherwise it is the number of objects
    chunksize: 1000

    # what to do
    bands: [g,r,i,z]

collate:
    # how to combine results
    concat_type: 'concat-des'
    blinding: "y3"


# for now do regular fitting
fitter_type: "max-ngmix-boot"
imageio_type: "meds-des-y3"

fit_me_galaxy: True
fit_coadd_galaxy: False

read_wcs: False
read_me_wcs: False

# turning off for ngmix only, since it currently
# requires all stamps same size

propagate_star_flags:
    # propagate SATURATE, INTERP between
    # bands and epochs
    propagate: True

    # don't propagate if these bits are also set for
    # the same pixel
    ignore_when_set: [
        SUSPECT,
        SSXTALK,
        EDGEBLEED,
        CRAY,
        BADAMP,
        BPM,
    ]


# throw out postage stamps for which the seg map of the
# central object intersects a bright star mask
flag_y1_stellarhalo_masked: False

# if > 0, will add in estimate for intrinsic profile variance 
intr_prof_var_fac: 0.0

# note this should not be set explicitly to false for mof runs
guess_from_nbrs: False

# do *not* do this in the main code, but in the neighbor
# code
reject_outliers: True

# the input images have zero weight when lots of bits are set
# Setting these will zero out more
extra_mask_flag_list: [
    TAPEBUMP,
    NEAREDGE,
    SATURATE,
    INTERP,
    #SUSPECT,
]


# don't bother with any images that have bad pixels or zero weight
# pixels
max_bmask_frac: 0.45
max_zero_weight_frac: 0.45

# don't need this since we are rejecting anything witha bad pixel
replace_bad_pixels: False

# no need for this, since we don't allow any bits set in mask
symmetrize_bmask: False

# don't need this since we are rejecting anything with zero weight
symmetrize_weight: False

# skip when either all weight or all image are zero
ignore_zero_weights_images: True


# skip if central region is masked
# this is a 4 pixel offset in each direction
# no need since we toss images with bad pixels
#central_bmask_radius: 4

#max_box_size: 48

# subtracting neighbors, so use regular weight
region: "cweight-nearest"

# flagging
#replacement_flags: "${DESDATA}/EXTRA/combined-image-flags/sva1_astrom_run1.0.1_stats_flagged_sheldon_psfv3_blacklists.json"

# astrom
# 2**0 + 2**1 + 2**2 + 2**3 + 2**5 + 2**6 + 2**7 + 2**8 + 2**9
#  = 1007
# blacklists
# 2**(10+0) + 2**(10+1) + 2**(10+2) + 2**(10+3) + 2**(10+4) = (31<<10)
#  = 31744
# psf
# 2**(15+0) + 2**(15+1) + 2**(15+4)
#  = (19<<15)
# total
# 
# 1007 + (31<<10) + (19<<15)
#  = 655343

image_flags2check: 655343

use_psf_rerun: False
normalize_psf: False
center_psf: False

print_params: True

max_pars:
    method: 'lm'
    ntry: 2
    
    lm_pars:
        maxfev: 2000
        xtol: 5.0e-5
        ftol: 5.0e-5

    use_fracdev_grid: False
    fracdev_range: [0.0,1.0]
    TdByTe_range: [0.0,1.0e+12]

psf_pars:
    model: 'em3'
    ntry: 20
    fit_pars:
      maxiter: 5000
      tol: 5.0e-6


round_pars:
    fitter_type: 'max'

replace_cov: False
cov_pars:
    m: 5
    h: 1.0e-3

use_logpars: False
model_pars:
    cm:
        g:
            type: "cosmos-sersic"

        T:
            type: "TwoSidedErf"
            pars: [-10.0, 0.03, 1.0e+06, 1.0e+05]

        counts:
            type: "TwoSidedErf"
            pars: [-1.0e+04, 1.0, 1.0e+09, 0.25e+08]
            repeat: True

        cen:
            type: "dgauss"
            width: 0.27

        # from fits on great-des
        fracdev:
            weights: [ 0.07219169,  0.03931063,  0.06144639,  0.02342249,  0.05680965,
                       0.07317471,  0.07112629,  0.05102051,  0.03397887,  0.06657475,
                       0.02908218,  0.01747496,  0.06998605,  0.00772567,  0.02882283,
                       0.04503099,  0.06212688,  0.06761242,  0.0502267 ,  0.07285532]
            means: [-0.0621139 ,  0.48460298, -0.16349622,  0.81232456,  0.1555424 ,
                     -0.08928717, -0.12935131,  0.25287222,  0.5998589 ,  0.01771045,
                     -0.21265698,  0.90599701, -0.02775166,  1.03471975,  0.7096433 ,
                     0.36650008,  0.07729925, -0.14636961, -0.18364023, -0.11087039]
            covars: [ 0.05039464,  0.14833301,  0.02533687,  0.08991854,  0.11303651,
                      0.04256832,  0.03219367,  0.13369827,  0.13584953,  0.07452398,
                      0.02094517,  0.0701313 ,  0.06071257,  0.05520489,  0.11392525,
                      0.14748899,  0.09209303,  0.02847802,  0.02259679,  0.03674909]


do_shear: False


# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,5,10,15,20,25,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420,
              480,540,
              600,700,
              800,900,1000,1200,1400,1600,1800,2000]
